//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.SkeletonBasics
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSerie
    {
        public int ID { get; set; }
        public int ID_TR { get; set; }
        public string Tipo_movimento { get; set; }
        public string Articulacao { get; set; }
        public string Posicao { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> Angulo { get; set; }
        public Nullable<int> Qt_acertos { get; set; }
        public Nullable<bool> Nivel_liberado { get; set; }
        public Nullable<bool> Nivel_concluido { get; set; }
        public Nullable<int> Qt_erros { get; set; }
        public Nullable<int> Score_nivel { get; set; }
        public Nullable<int> Qt_rep_nivel { get; set; }
        public string Observacao { get; set; }
    
        public virtual TBTratamento TBTratamento { get; set; }
    }
}
