//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.SkeletonBasics
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBTratamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBTratamento()
        {
            this.TBSerie = new HashSet<TBSerie>();
        }
    
        public int ID_TR { get; set; }
        public int ID_User_PC { get; set; }
        public string Patologia { get; set; }
        public string Objetivo { get; set; }
        public string Observacao { get; set; }
        public int ID_User_FS { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBSerie> TBSerie { get; set; }
        public virtual TBUser TBUser { get; set; }
        public virtual TBUser TBUser1 { get; set; }
        public virtual TBUser TBUser2 { get; set; }
    }
}
